a:4:{s:4:"urls";a:8:{s:34:"/our-work/westlake-plastic-surgery";a:3:{s:6:"folder";s:8:"our-work";s:4:"path";s:43:"/01-our-work/01.westlake-plastic-surgery.md";s:4:"file";s:30:"01.westlake-plastic-surgery.md";}s:22:"/our-work/mcaden-homes";a:3:{s:6:"folder";s:8:"our-work";s:4:"path";s:31:"/01-our-work/02.mcaden-homes.md";s:4:"file";s:18:"02.mcaden-homes.md";}s:28:"/our-work/apollo-endosurgery";a:3:{s:6:"folder";s:8:"our-work";s:4:"path";s:37:"/01-our-work/03.apollo-endosurgery.md";s:4:"file";s:24:"03.apollo-endosurgery.md";}s:31:"/our-work/travis-peak-resources";a:3:{s:6:"folder";s:8:"our-work";s:4:"path";s:40:"/01-our-work/04.travis-peak-resources.md";s:4:"file";s:27:"04.travis-peak-resources.md";}s:28:"/our-work/sanregret-weddings";a:3:{s:6:"folder";s:8:"our-work";s:4:"path";s:37:"/01-our-work/05.sanregret-weddings.md";s:4:"file";s:24:"05.sanregret-weddings.md";}s:9:"/our-work";a:3:{s:6:"folder";s:1:"/";s:4:"path";s:20:"/01-our-work/page.md";s:4:"file";s:16:"our-work/page.md";}s:4:"/404";a:3:{s:6:"folder";s:1:"/";s:4:"path";s:7:"/404.md";s:4:"file";s:6:"404.md";}s:1:"/";a:3:{s:6:"folder";s:1:"/";s:4:"path";s:8:"/page.md";s:4:"file";s:8:"/page.md";}}s:7:"content";a:2:{s:8:"our-work";a:5:{s:30:"01.westlake-plastic-surgery.md";a:5:{s:6:"folder";s:8:"our-work";s:4:"path";s:43:"/01-our-work/01.westlake-plastic-surgery.md";s:4:"file";s:30:"01.westlake-plastic-surgery.md";s:3:"url";s:34:"/our-work/westlake-plastic-surgery";s:4:"data";a:27:{s:10:"main_image";s:42:"/img/portfolio-images/devices-westlake.png";s:5:"title";s:24:"Westlake Plastic Surgery";s:19:"project_screenshots";a:3:{i:0;a:1:{s:10:"screenshot";s:53:"/img/portfolio-images/WestlakePlasticSurgery-home.jpg";}i:1;a:1:{s:10:"screenshot";s:55:"/img/portfolio-images/WestlakePlasticSurgery-photos.jpg";}i:2;a:1:{s:10:"screenshot";s:55:"/img/portfolio-images/WestlakePlasticSurgery-videos.jpg";}}s:19:"project_description";s:457:"<p>
	 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:8:"featured";s:1:"1";s:17:"short_description";s:116:"<p>
	This is a description of the client and the project. It will be very brief and just get people interested.
</p>";s:7:"content";s:4:"true";s:11:"content_raw";s:4:"true";s:5:"_file";s:85:"/Applications/MAMP/htdocs/UnitTwo/_content/01-our-work/01.westlake-plastic-surgery.md";s:11:"_local_path";s:43:"/01-our-work/01.westlake-plastic-surgery.md";s:10:"_order_key";s:2:"01";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";s:2:"01";s:13:"last_modified";i:1395951868;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:24:"westlake-plastic-surgery";s:7:"_folder";s:8:"our-work";s:9:"_basename";s:30:"01.westlake-plastic-surgery.md";s:9:"_filename";s:27:"01.westlake-plastic-surgery";s:9:"_is_entry";i:1;s:8:"_is_page";i:1;s:3:"url";s:34:"/our-work/westlake-plastic-surgery";s:9:"permalink";s:52:"http://unittwo.dev/our-work/westlake-plastic-surgery";}}s:18:"02.mcaden-homes.md";a:5:{s:6:"folder";s:8:"our-work";s:4:"path";s:31:"/01-our-work/02.mcaden-homes.md";s:4:"file";s:18:"02.mcaden-homes.md";s:3:"url";s:22:"/our-work/mcaden-homes";s:4:"data";a:27:{s:10:"main_image";s:40:"/img/portfolio-images/devices-mcaden.jpg";s:5:"title";s:12:"McAden Homes";s:19:"project_screenshots";a:3:{i:0;a:1:{s:10:"screenshot";s:37:"/img/portfolio-images/McAden-home.jpg";}i:1;a:1:{s:10:"screenshot";s:38:"/img/portfolio-images/McAden-homes.jpg";}i:2;a:1:{s:10:"screenshot";s:43:"/img/portfolio-images/McAden-commercial.jpg";}}s:17:"short_description";s:166:"<p>
	Based in Austin, McAden Builders is a premier builder of luxury custom homes and commercial properties. We completed a major website overhaul in early 2014.
</p>";s:19:"project_description";s:456:"<p>
	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:8:"featured";s:1:"1";s:7:"content";s:4:"true";s:11:"content_raw";s:4:"true";s:5:"_file";s:73:"/Applications/MAMP/htdocs/UnitTwo/_content/01-our-work/02.mcaden-homes.md";s:11:"_local_path";s:31:"/01-our-work/02.mcaden-homes.md";s:10:"_order_key";s:2:"02";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";s:2:"02";s:13:"last_modified";i:1395951926;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:12:"mcaden-homes";s:7:"_folder";s:8:"our-work";s:9:"_basename";s:18:"02.mcaden-homes.md";s:9:"_filename";s:15:"02.mcaden-homes";s:9:"_is_entry";i:1;s:8:"_is_page";i:1;s:3:"url";s:22:"/our-work/mcaden-homes";s:9:"permalink";s:40:"http://unittwo.dev/our-work/mcaden-homes";}}s:24:"03.apollo-endosurgery.md";a:5:{s:6:"folder";s:8:"our-work";s:4:"path";s:37:"/01-our-work/03.apollo-endosurgery.md";s:4:"file";s:24:"03.apollo-endosurgery.md";s:3:"url";s:28:"/our-work/apollo-endosurgery";s:4:"data";a:27:{s:10:"main_image";s:40:"/img/portfolio-images/devices-apollo.jpg";s:5:"title";s:18:"Apollo Endosurgery";s:19:"project_screenshots";a:4:{i:0;a:1:{s:10:"screenshot";s:48:"/img/portfolio-images/ApolloEndosurgery-home.jpg";}i:1;a:1:{s:10:"screenshot";s:41:"/img/portfolio-images/Apollo-products.jpg";}i:2;a:1:{s:10:"screenshot";s:47:"/img/portfolio-images/Apollo-product-detail.jpg";}i:3;a:1:{s:10:"screenshot";s:36:"/img/portfolio-images/Apollo-map.jpg";}}s:19:"project_description";s:457:"<p>
	 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:8:"featured";s:1:"1";s:17:"short_description";s:217:"<p>
	Apollo develops cutting-edge surgical instruments that allow surgeons to perform minimally-invasive endoscopic surgery. We built and maintain their entire IT infrastructure and rebuilt their website in 2013.
</p>";s:7:"content";s:4:"true";s:11:"content_raw";s:4:"true";s:5:"_file";s:79:"/Applications/MAMP/htdocs/UnitTwo/_content/01-our-work/03.apollo-endosurgery.md";s:11:"_local_path";s:37:"/01-our-work/03.apollo-endosurgery.md";s:10:"_order_key";s:2:"03";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";s:2:"03";s:13:"last_modified";i:1395951956;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:18:"apollo-endosurgery";s:7:"_folder";s:8:"our-work";s:9:"_basename";s:24:"03.apollo-endosurgery.md";s:9:"_filename";s:21:"03.apollo-endosurgery";s:9:"_is_entry";i:1;s:8:"_is_page";i:1;s:3:"url";s:28:"/our-work/apollo-endosurgery";s:9:"permalink";s:46:"http://unittwo.dev/our-work/apollo-endosurgery";}}s:27:"04.travis-peak-resources.md";a:5:{s:6:"folder";s:8:"our-work";s:4:"path";s:40:"/01-our-work/04.travis-peak-resources.md";s:4:"file";s:27:"04.travis-peak-resources.md";s:3:"url";s:31:"/our-work/travis-peak-resources";s:4:"data";a:27:{s:10:"main_image";s:44:"/img/portfolio-images/devices-travispeak.jpg";s:5:"title";s:21:"Travis Peak Resources";s:19:"project_screenshots";a:3:{i:0;a:1:{s:10:"screenshot";s:41:"/img/portfolio-images/TravisPeak-home.jpg";}i:1;a:1:{s:10:"screenshot";s:41:"/img/portfolio-images/TravisPeak-team.jpg";}i:2;a:1:{s:10:"screenshot";s:44:"/img/portfolio-images/TravisPeak-careers.jpg";}}s:19:"project_description";s:457:"<p>
	 Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:8:"featured";s:1:"1";s:17:"short_description";s:147:"<p>
	Founded in 2013, this petroleum exploration company turned to us to build their IT infrastructure and create their initial web prescence.
</p>";s:7:"content";s:4:"true";s:11:"content_raw";s:4:"true";s:5:"_file";s:82:"/Applications/MAMP/htdocs/UnitTwo/_content/01-our-work/04.travis-peak-resources.md";s:11:"_local_path";s:40:"/01-our-work/04.travis-peak-resources.md";s:10:"_order_key";s:2:"04";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";s:2:"04";s:13:"last_modified";i:1395951979;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:21:"travis-peak-resources";s:7:"_folder";s:8:"our-work";s:9:"_basename";s:27:"04.travis-peak-resources.md";s:9:"_filename";s:24:"04.travis-peak-resources";s:9:"_is_entry";i:1;s:8:"_is_page";i:1;s:3:"url";s:31:"/our-work/travis-peak-resources";s:9:"permalink";s:49:"http://unittwo.dev/our-work/travis-peak-resources";}}s:24:"05.sanregret-weddings.md";a:5:{s:6:"folder";s:8:"our-work";s:4:"path";s:37:"/01-our-work/05.sanregret-weddings.md";s:4:"file";s:24:"05.sanregret-weddings.md";s:3:"url";s:28:"/our-work/sanregret-weddings";s:4:"data";a:24:{s:5:"title";s:18:"Sanregret Weddings";s:19:"project_description";s:459:"<p>
	   Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:19:"project_screenshots";a:3:{i:0;a:1:{s:10:"screenshot";s:40:"/img/portfolio-images/Sanregret-home.jpg";}i:1;a:1:{s:10:"screenshot";s:44:"/img/portfolio-images/Sanregret-weddings.jpg";}i:2;a:1:{s:10:"screenshot";s:50:"/img/portfolio-images/Sanregret-wedding-detail.jpg";}}s:10:"main_image";s:43:"/img/portfolio-images/sanregret-devices.jpg";s:17:"short_description";s:186:"<p>
	 Jennifer Sanregret makes people's wedding-day dreams come true. She needed a website that exuded simple elegance. We created a beautiful platform for displaying her expertise.
</p>";s:5:"_file";s:79:"/Applications/MAMP/htdocs/UnitTwo/_content/01-our-work/05.sanregret-weddings.md";s:11:"_local_path";s:37:"/01-our-work/05.sanregret-weddings.md";s:10:"_order_key";s:2:"05";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";s:2:"05";s:13:"last_modified";i:1395952325;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:18:"sanregret-weddings";s:7:"_folder";s:8:"our-work";s:9:"_basename";s:24:"05.sanregret-weddings.md";s:9:"_filename";s:21:"05.sanregret-weddings";s:9:"_is_entry";i:1;s:8:"_is_page";i:1;s:3:"url";s:28:"/our-work/sanregret-weddings";s:9:"permalink";s:46:"http://unittwo.dev/our-work/sanregret-weddings";}}}s:1:"/";a:3:{s:16:"our-work/page.md";a:5:{s:6:"folder";s:1:"/";s:4:"path";s:20:"/01-our-work/page.md";s:4:"file";s:16:"our-work/page.md";s:3:"url";s:9:"/our-work";s:4:"data";a:22:{s:5:"title";s:8:"Our Work";s:22:"_default_folder_layout";s:16:"default_interior";s:24:"_default_folder_template";s:14:"portfolio-item";s:5:"_file";s:62:"/Applications/MAMP/htdocs/UnitTwo/_content/01-our-work/page.md";s:11:"_local_path";s:20:"/01-our-work/page.md";s:10:"_order_key";s:2:"01";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";s:2:"01";s:13:"last_modified";i:1395957259;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:4:"page";s:7:"_folder";s:1:"/";s:9:"_basename";s:7:"page.md";s:9:"_filename";s:4:"page";s:9:"_is_entry";i:0;s:8:"_is_page";i:1;s:3:"url";s:9:"/our-work";s:9:"permalink";s:27:"http://unittwo.dev/our-work";}}s:6:"404.md";a:5:{s:6:"folder";s:1:"/";s:4:"path";s:7:"/404.md";s:4:"file";s:6:"404.md";s:3:"url";s:4:"/404";s:4:"data";a:22:{s:5:"title";s:27:"Not All Who Wander Are Lost";s:7:"content";s:4:"true";s:11:"content_raw";s:4:"true";s:5:"_file";s:49:"/Applications/MAMP/htdocs/UnitTwo/_content/404.md";s:11:"_local_path";s:7:"/404.md";s:10:"_order_key";N;s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";N;s:13:"last_modified";i:1392410266;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:3:"404";s:7:"_folder";s:1:"/";s:9:"_basename";s:6:"404.md";s:9:"_filename";s:3:"404";s:9:"_is_entry";i:0;s:8:"_is_page";i:1;s:3:"url";s:4:"/404";s:9:"permalink";s:22:"http://unittwo.dev/404";}}s:8:"/page.md";a:5:{s:6:"folder";s:1:"/";s:4:"path";s:8:"/page.md";s:4:"file";s:8:"/page.md";s:3:"url";s:1:"/";s:4:"data";a:26:{s:5:"title";s:4:"Home";s:9:"_fieldset";s:8:"homepage";s:9:"_template";s:4:"home";i:0;s:3:"___";s:10:"intro_text";s:213:"<p>
	  Austin, TX based IT consulting firm Robo6K and web development shop Backbeat Web have joined forces! We call this partnership UnitTwo. Together we offer our clients a full suite of IT and web services.
</p>";s:12:"web_services";a:3:{i:0;a:3:{s:13:"project_title";s:17:"Responsive Design";s:19:"project_description";s:405:"<p>
	  Most websites receive 50% or more of their traffic from small-screen devices like phones and tablets. Therefore, your site must look great and function perfectly on all types of devices. We use our expert design sense and knowledge of the latest techniques to make sure your customers receive an outstanding experience on large desktop monitors, laptops, iPhones, iPads, and all other devices.
</p>";s:13:"project_image";s:27:"/assets/icon-responsive.png";}i:1;a:3:{s:13:"project_title";s:26:"Content Management Systems";s:19:"project_description";s:406:"<p>
	  What good is having a great-looking site if you can't easily update the content? Keeping your content fresh is a must to keep potential customers coming back. Search engines such as Google rank your site higher when content is updated frequently. We build sites on easy-to-use CMS platforms such as WordPress, Craft, and Statamic, making updating and adding new pages, news, and blogs a breeze!
</p>";s:13:"project_image";s:23:"/assets/icon-pencil.png";}i:2;a:3:{s:13:"project_title";s:18:"Custom Development";s:19:"project_description";s:279:"<p>
	  Many web development agencies squeeze their clients' sites into one-size-fits-all, off-the-shelf themes or templates. We don't take shortcuts. All of our sites are custom designed and built - assuring our clients' sites are unique and reflect their message and brand.
</p>";s:13:"project_image";s:22:"/assets/icon-gears.png";}}s:11:"it_services";a:5:{i:0;a:3:{s:13:"project_title";s:33:"Network and Server Infrastructure";s:19:"project_description";s:460:"<p>
	  Network ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:13:"project_image";s:24:"/assets/icon-network.png";}i:1;a:3:{s:13:"project_title";s:28:"Hardware and Desktop Support";s:19:"project_description";s:461:"<p>
	  Hardware ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:13:"project_image";s:22:"/assets/icon-mouse.png";}i:2;a:3:{s:13:"project_title";s:22:"Exchange Email Hosting";s:19:"project_description";s:461:"<p>
	  Exchange ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:13:"project_image";s:22:"/assets/icon-email.png";}i:3;a:3:{s:13:"project_title";s:18:"Sharepoint Hosting";s:19:"project_description";s:463:"<p>
	  Sharepoint ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:13:"project_image";s:27:"/assets/icon-sharepoint.png";}i:4;a:3:{s:13:"project_title";s:10:"Consulting";s:19:"project_description";s:460:"<p>
	  Gruyere ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>";s:13:"project_image";s:24:"/assets/icon-callout.png";}}s:5:"_file";s:50:"/Applications/MAMP/htdocs/UnitTwo/_content/page.md";s:11:"_local_path";s:8:"/page.md";s:10:"_order_key";s:7:"page.md";s:13:"datetimestamp";N;s:9:"datestamp";N;s:4:"date";N;s:4:"time";N;s:7:"numeric";N;s:13:"last_modified";i:1395954108;s:10:"_is_hidden";b:0;s:9:"_is_draft";b:0;s:4:"slug";s:4:"page";s:7:"_folder";s:1:"/";s:9:"_basename";s:7:"page.md";s:9:"_filename";s:4:"page";s:9:"_is_entry";i:0;s:8:"_is_page";i:1;s:3:"url";s:1:"/";s:9:"permalink";s:19:"http://unittwo.dev/";}}}}s:10:"taxonomies";a:2:{s:10:"categories";a:0:{}s:4:"tags";a:0:{}}s:9:"structure";a:0:{}}